### ISSUE TITLE
Joining efforts

### ISSUE THREAD

**Issue by leojrfs** [larsimmisch/homebrew-avr#24]
There are plenty repos as:
https://github.com/jpommerening/homebrew-avr
https://github.com/larsimmisch/homebrew-avr
https://github.com/WeAreLeka/homebrew-avr

What do you think of joining efforts and avoiding duplication, by creating an org like homebrew-uC/homebrew-avr

And then we can also join suff from other uC archs :smiley:

i am also posting the same issue on the listed repos

**Comment by nixpulvis** [comment]
:+1:
