### ISSUE TITLE
sha1 being deprecated

### ISSUE THREAD

**Issue by tchapi** [larsimmisch/homebrew-avr#28]
Hi,

I have the following warning for deprecation when using your tap : 

```
Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/larsimmisch/homebrew-avr/avr-binutils.rb:7:in `<class:AvrBinutils>'
Please report this to the larsimmisch/avr tap!
```

Anything you can do ?
See https://github.com/Homebrew/brew/issues/606 for details

Best regards,
Cyril

**Comment by tchapi** [comment]
_Oops_, didn't see this repo was deprecated — my bad !

**Comment by larsimmisch** [comment]
Your exact issue was resolved very recently on the successor project: https://github.com/osx-cross/homebrew-avr/pull/31
