### ISSUE TITLE
Calling Formula.sha1 is disabled!

### ISSUE THREAD

**Issue by vcavallo** [larsimmisch/homebrew-avr#29]
Hello. In trying to install `avr-gcc` I got the following error:

```
$ brew install larsimmisch/avr/avr-gcc
Error: Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/larsimmisch/homebrew-avr/avr-gcc.rb:7:in `<class:AvrGcc>'
Please report this to the larsimmisch/avr tap!
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/larsimmisch/homebrew-avr/issues
```

Let me know what else you'd need from me to help.
Thanks!

**Comment by larsimmisch** [comment]
The **Readme** states:

This repository is deprecated - all new work is being done on https://github.com/osx-cross/homebrew-avr/

So please `untap` this repo and try with https://github.com/osx-cross/homebrew-avr/
